const { Session } = require('./src/engine');
const { review } = require('./src/report');

const s = new Session().chooseOrder(['terry','ray','ruth']);
['Why does the log exist?','Who reads the log?','Have you ever seen anyone pull it up?','What do you tell them when they call?'].forEach(q=>s.ask(q));
s.advanceWindow();
['How many claims a day?','Do we send anything back to them?','What is the turnaround from the vendor?'].forEach(q=>s.ask(q));
s.advanceWindow();
['Is there anything you catch that nothing else would?','Do you get many repeat claims?','How long is the gap between copies?'].forEach(q=>s.ask(q));

const J='Documented during interviews.';
const submission = {
  rootCause: 'Providers re-send because nothing acknowledges receipt. The repeat volume is generated by our own latency.',
  rows: {
    intake:{disposition:'automate',justification:J},
    log:{disposition:'eliminate',justification:J},
    vendor:{disposition:'cannot_assess',justification:J},
    review:{disposition:'automate',justification:J}
  }
};

const r = review(submission, s.transcript);
console.log('\n=== INSTRUCTOR VIEW ===\n');
console.log('Root cause as written:\n  "' + r.rootCause + '"\n');
console.log('Harm fired:', r.harmFired);
for (const c of r.consequences) console.log(`  ${c.rowId.padEnd(7)} ${c.disposition.padEnd(14)} [${c.severity}]`);
console.log('\nEvidence held (' + r.evidence.held.length + '/' + (r.evidence.held.length+r.evidence.missed.length) + '):');
r.evidence.held.forEach(e=>console.log('  + ' + e.label));
console.log('\nNot reached:');
r.evidence.missed.forEach(e=>console.log('  - ' + e.label));
console.log('\nLoop available to them:', r.evidence.loopAvailable);
console.log('\nHARM:\n  ' + r.harm.map(h=>h.consequence).join('\n  '));
